[package]
name = "plrust"
version = "0.0.0"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
edition = "2018"
license = "PostgreSQL Open Source License"
description = "A Rust procedural language for PostgreSQL"
homepage = "https://github.com/zombodb/plrust/"
repository = "https://github.com/zombodb/plrust/"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg12"]
pg10 = ["pgx/pg10", "pgx-tests/pg10"]
pg11 = ["pgx/pg11", "pgx-tests/pg11"]
pg12 = ["pgx/pg12", "pgx-tests/pg12"]
pg13 = ["pgx/pg13", "pgx-tests/pg13"]
pg_test = []
# Be accomodating to sandboxed builds with no network.
sandboxed = []

[dependencies]
pgx = { git = "https://github.com/zombodb/pgx", branch = "no-thread-locals" }
pgx-macros = { git = "https://github.com/zombodb/pgx", branch = "no-thread-locals" }
libloading = "0.6.4"
cfg-if = "1"

[dev-dependencies]
pgx-tests = { git = "https://github.com/zombodb/pgx", branch = "no-thread-locals" }
tempdir = "0.3.7"
once_cell = "1.7.2"
toml = "0.5.8"
pgx-utils = { git = "https://github.com/zombodb/pgx", branch = "no-thread-locals" }
pgx-pg-sys = { git = "https://github.com/zombodb/pgx", branch = "no-thread-locals" }

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
