on: [push]

jobs:          
  check:
    strategy:
      matrix:
        pg_version:
          - 10
          - 11
          - 12
          - 13
        target:
          - runs-on: ubuntu-latest
            triple: aarch64-unknown-linux-gnu
          - runs-on: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
          - runs-on: macos-latest
            triple: x86_64-apple-darwin

    runs-on: ${{ matrix.target.runs-on }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.target.runs-on }}-${{ matrix.target.triple }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
          target: ${{ matrix.target.triple }}

      - run:
          cargo install cargo-pgx
          cargo pgx init

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build --target ${{matrix.target.triple }} --no-default-features --features "${{ matrix.pg_version }}"

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test --target ${{matrix.target.triple }} --no-default-features --features "${{ matrix.pg_version }}"

